version: '3.3'

services:
  php-apache:
    build:
      context: .
      dockerfile: IaC/php-apache/Dockerfile
    container_name: tecnofit_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - tecnofit_network
  db:
    image: mysql:8.0
    container_name: tecnofit_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecnofit
      MYSQL_USER: tecnofit_user
      MYSQL_PASSWORD: tecnofit_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tecnofit_network

volumes:
  db_data:

networks:
  tecnofit_network:
    driver: bridge
